/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.test.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Book service. Represents a row in the &quot;TB_Book&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.test.portlet.model.impl.BookModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.test.portlet.model.impl.BookImpl}.
 * </p>
 *
 * @author kmv
 * @see Book
 * @see com.liferay.test.portlet.model.impl.BookImpl
 * @see com.liferay.test.portlet.model.impl.BookModelImpl
 * @generated
 */
public interface BookModel extends BaseModel<Book> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a book model instance should use the {@link Book} interface instead.
	 */

	/**
	 * Returns the primary key of this book.
	 *
	 * @return the primary key of this book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this book.
	 *
	 * @param primaryKey the primary key of this book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the book ID of this book.
	 *
	 * @return the book ID of this book
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this book.
	 *
	 * @param bookId the book ID of this book
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the genre ID of this book.
	 *
	 * @return the genre ID of this book
	 */
	public long getGenreId();

	/**
	 * Sets the genre ID of this book.
	 *
	 * @param genreId the genre ID of this book
	 */
	public void setGenreId(long genreId);

	/**
	 * Returns the publisher ID of this book.
	 *
	 * @return the publisher ID of this book
	 */
	public long getPublisherId();

	/**
	 * Sets the publisher ID of this book.
	 *
	 * @param publisherId the publisher ID of this book
	 */
	public void setPublisherId(long publisherId);

	/**
	 * Returns the author ID of this book.
	 *
	 * @return the author ID of this book
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this book.
	 *
	 * @param authorId the author ID of this book
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the name of this book.
	 *
	 * @return the name of this book
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this book.
	 *
	 * @param name the name of this book
	 */
	public void setName(String name);

	/**
	 * Returns the release date of this book.
	 *
	 * @return the release date of this book
	 */
	@AutoEscape
	public String getReleaseDate();

	/**
	 * Sets the release date of this book.
	 *
	 * @param releaseDate the release date of this book
	 */
	public void setReleaseDate(String releaseDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.test.portlet.model.Book book);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.test.portlet.model.Book> toCacheModel();

	@Override
	public com.liferay.test.portlet.model.Book toEscapedModel();

	@Override
	public com.liferay.test.portlet.model.Book toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}