/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.test.portlet.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.test.portlet.model.Genre;
import com.liferay.test.portlet.model.GenreModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Genre service. Represents a row in the &quot;TB_Genre&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.test.portlet.model.GenreModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GenreImpl}.
 * </p>
 *
 * @author kmv
 * @see GenreImpl
 * @see com.liferay.test.portlet.model.Genre
 * @see com.liferay.test.portlet.model.GenreModel
 * @generated
 */
public class GenreModelImpl extends BaseModelImpl<Genre> implements GenreModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a genre model instance should use the {@link com.liferay.test.portlet.model.Genre} interface instead.
	 */
	public static final String TABLE_NAME = "TB_Genre";
	public static final Object[][] TABLE_COLUMNS = {
			{ "genreId", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table TB_Genre (genreId LONG not null primary key,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TB_Genre";
	public static final String ORDER_BY_JPQL = " ORDER BY genre.genreId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TB_Genre.genreId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.test.portlet.model.Genre"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.test.portlet.model.Genre"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.test.portlet.model.Genre"));

	public GenreModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _genreId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGenreId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _genreId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Genre.class;
	}

	@Override
	public String getModelClassName() {
		return Genre.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("genreId", getGenreId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long genreId = (Long)attributes.get("genreId");

		if (genreId != null) {
			setGenreId(genreId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@Override
	public long getGenreId() {
		return _genreId;
	}

	@Override
	public void setGenreId(long genreId) {
		_genreId = genreId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Genre.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Genre toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Genre)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GenreImpl genreImpl = new GenreImpl();

		genreImpl.setGenreId(getGenreId());
		genreImpl.setName(getName());

		genreImpl.resetOriginalValues();

		return genreImpl;
	}

	@Override
	public int compareTo(Genre genre) {
		long primaryKey = genre.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Genre)) {
			return false;
		}

		Genre genre = (Genre)obj;

		long primaryKey = genre.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Genre> toCacheModel() {
		GenreCacheModel genreCacheModel = new GenreCacheModel();

		genreCacheModel.genreId = getGenreId();

		genreCacheModel.name = getName();

		String name = genreCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			genreCacheModel.name = null;
		}

		return genreCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{genreId=");
		sb.append(getGenreId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.liferay.test.portlet.model.Genre");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>genreId</column-name><column-value><![CDATA[");
		sb.append(getGenreId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Genre.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Genre.class };
	private long _genreId;
	private String _name;
	private Genre _escapedModel;
}