/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.test.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Publisher service. Represents a row in the &quot;TB_Publisher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.test.portlet.model.impl.PublisherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.test.portlet.model.impl.PublisherImpl}.
 * </p>
 *
 * @author kmv
 * @see Publisher
 * @see com.liferay.test.portlet.model.impl.PublisherImpl
 * @see com.liferay.test.portlet.model.impl.PublisherModelImpl
 * @generated
 */
public interface PublisherModel extends BaseModel<Publisher> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a publisher model instance should use the {@link Publisher} interface instead.
	 */

	/**
	 * Returns the primary key of this publisher.
	 *
	 * @return the primary key of this publisher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this publisher.
	 *
	 * @param primaryKey the primary key of this publisher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the publisher ID of this publisher.
	 *
	 * @return the publisher ID of this publisher
	 */
	public long getPublisherId();

	/**
	 * Sets the publisher ID of this publisher.
	 *
	 * @param publisherId the publisher ID of this publisher
	 */
	public void setPublisherId(long publisherId);

	/**
	 * Returns the name of this publisher.
	 *
	 * @return the name of this publisher
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this publisher.
	 *
	 * @param name the name of this publisher
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.test.portlet.model.Publisher publisher);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.test.portlet.model.Publisher> toCacheModel();

	@Override
	public com.liferay.test.portlet.model.Publisher toEscapedModel();

	@Override
	public com.liferay.test.portlet.model.Publisher toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}